### ISSUE TITLE
seed parameter error when use DataDreamer with VLLM 

### ISSUE THREAD

**Issue by yuqie** [datadreamer-dev/DataDreamer#24]
Hi, I am trying use open source LLMs to generate data. So I modifed the "Abstract to Tweet Model" demo script and substitute OpenAI with VLLM as following.

The script I used (refer the demo https://datadreamer.dev/docs/latest/pages/get_started/quick_tour/abstract_to_tweet.html)
```
from datadreamer import DataDreamer
from datadreamer.llms import VLLM
from datadreamer.steps import DataFromPrompt, ProcessWithPrompt
from datadreamer.trainers import TrainHFFineTune
from peft import LoraConfig

with DataDreamer("./output"):
    llama2_7b = VLLMmodel_name="llama2_7b",device=0)

    # Generate synthetic arXiv-style research paper abstracts with llama2_7b
    arxiv_dataset = DataFromPrompt(
        "Generate Research Paper Abstracts",
        args={
            "llm": llama2_7b,
            "n": 1000,
            "temperature": 1.2,
            "instruction": (
                "Generate an arXiv abstract of an NLP research paper."
                " Return just the abstract, no titles."
            ),
        },
        outputs={"generations": "abstracts"},
    )

    # Ask llama2_7b to convert the abstracts to tweets
    abstracts_and_tweets = ProcessWithPrompt(
        "Generate Tweets from Abstracts",
        inputs={"inputs": arxiv_dataset.output["abstracts"]},
        args={
            "llm": llama2_7b,
            "instruction": (
                "Given the abstract, write a tweet to summarize the work."
            ),
            "top_p": 1.0,
        },
        outputs={"inputs": "abstracts", "generations": "tweets"},
    )
```

Following is the error I encountered.
```
[ 🤖 DataDreamer 💤 ] Initialized. 🚀 Dreaming to folder: ./output_dd
[ 🤖 DataDreamer 💤 ] Step 'Generate Research Paper Abstracts' is running. ⏳
INFO 04-28 02:24:16 selector.py:45] Cannot use FlashAttention because the package is not found. Please install it for better performance.
INFO 04-28 02:24:16 selector.py:45] Cannot use FlashAttention because the package is not found. Please install it for better performance.
INFO 04-28 02:24:16 selector.py:21] Using XFormers backend.
INFO 04-28 02:24:16 selector.py:21] Using XFormers backend.
[ 🤖 DataDreamer 💤 ] [ 🧠 VLLM (/home/public_data/llama_2/llama-2-7b-hf/)] Loading...
[ 🤖 DataDreamer 💤 ] [ 🧠 VLLM (/home/public_data/llama_2/llama-2-7b-hf/)] Finished loading.
[ 🤖 DataDreamer 💤 ] Done. ✨ Results in folder: ./output_dd
Traceback (most recent call last):
  File "/home/qiey/QAGeneration/datadreamer_test.py", line 12, in <module>
    arxiv_dataset = DataFromPrompt(
                    ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/step.py", line 337, in __init__
    self.__setup_folder_and_resume()
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/step.py", line 442, in __setup_folder_and_resume
    self.__start()
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/step.py", line 451, in __start
    self._set_output(self.run())
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/step.py", line 894, in _set_output
    self.__output = _output_to_dataset(
                    ^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/step_output.py", line 862, in _output_to_dataset
    output = __output_to_dataset(
             ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/step_output.py", line 559, in __output_to_dataset
    first_row = next(
                ^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/steps/prompt/_prompt_base.py", line 115, in get_generations
    for prompt, generation, get_extra_columns in zip(
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/_cachable/_cachable.py", line 797, in _run_over_batches
    yield from self._run_over_batches_locked(
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/_cachable/_cachable.py", line 763, in _run_over_batches_locked
    results = self._run_over_sorted_batches(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/_cachable/_cachable.py", line 585, in _run_over_sorted_batches
    run_batch(
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/llms/vllm.py", line 209, in _run_batch
    generated_texts_batch = self.model.proxy.get_generated_texts_batch(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/Pyro5/client.py", line 510, in __call__
    return self.__send(self.__name, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/Pyro5/client.py", line 275, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
    ^^^^^^^^^^
TypeError: _StrWithSeed.__new__() missing 1 required positional argument: 'seed'
```
I tried to add seed parameter in VLLM, but following error is ecounterred.
```
  File "/root/anaconda3/envs/datadreamer/lib/python3.11/site-packages/datadreamer/llms/vllm.py", line 178, in _run_batch
    assert seed is None, f"`seed` is not supported for {type(self).__name__}"
           ^^^^^^^^^^^^
AssertionError: `seed` is not supported for VLLM
```
Could anyone tell me how to run Datadreamer data generation with VLLM and local models? 
Any suggestions would be appreciated.

**Comment by AjayP13** [comment]
Fixed in version 0.32.0 if you update your `datadreamer.dev` install from PyPI.
