### ISSUE TITLE
MistralAI Read Timeout

### ISSUE THREAD

**Issue by preemware** [datadreamer-dev/DataDreamer#8]
Problem tends to happens when using Mistral API on larger amount of entries. I'm using `mistral-large-latest`.

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/data/filter.py", line 24, in <module>
    filtered = FilterWithPrompt(
               ^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 337, in __init__
    self.__setup_folder_and_resume()
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 442, in __setup_folder_and_resume
    self.__start()
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 451, in __start
    self._set_output(self.run())
                     ^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/prompt/filter_with_prompt.py", line 84, in run
    process_with_prompt = ProcessWithPrompt(
                          ^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 337, in __init__
    self.__setup_folder_and_resume()
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 442, in __setup_folder_and_resume
    self.__start()
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 451, in __start
    self._set_output(self.run())
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step.py", line 894, in _set_output
    self.__output = _output_to_dataset(
                    ^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step_output.py", line 862, in _output_to_dataset
    output = __output_to_dataset(
             ^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/step_output.py", line 559, in __output_to_dataset
    first_row = next(
                ^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/steps/prompt/_prompt_base.py", line 105, in get_generations
    for input, prompt, generation, get_extra_columns in zip(
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/_cachable/_cachable.py", line 797, in _run_over_batches
    yield from self._run_over_batches_locked(
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/_cachable/_cachable.py", line 763, in _run_over_batches_locked
    results = self._run_over_sorted_batches(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/_cachable/_cachable.py", line 585, in _run_over_sorted_batches
    run_batch(
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/llms/mistral_ai.py", line 162, in _run_batch
    generated_texts_batch = list(
                            ^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/llms/mistral_ai.py", line 143, in get_generated_texts
    response = self.retry_wrapper(
               ^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/data/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/datadreamer/llms/mistral_ai.py", line 81, in _retry_wrapper
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/root/data/venv/lib/python3.11/site-packages/mistralai/client.py", line 160, in chat
    for response in single_response:
  File "/root/data/venv/lib/python3.11/site-packages/mistralai/client.py", line 98, in _request
    raise MistralException(
mistralai.exceptions.MistralException: Unexpected exception (ReadTimeout): The read operation timed out
```

**Comment by AjayP13** [comment]
Hi, thanks for the report, I believe this should be fixed on the newest version (0.21.0). We now catch these errors and retry: https://github.com/datadreamer-dev/DataDreamer/commit/4981802f5cfab8ca40597068baa9afd75750dc77
